Presentation/Pages/Admin/Categories/Add.cshtml.cs
using Application.Common.Models;
using Application.CQRS.Categories.Commands.CreateCategory;
using Application.CQRS.CategoryTranslations.Commands.CreateCategoryTranslation;
using Application.CQRS.Languages.Queries.GetLanguageByCode;
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;
using Serilog;
using System.Transactions;

namespace Presentation.Pages.Admin.Categ
{
    [Authorize(Roles = RoleAccessLevels.AdminAndModerator)]
    public class AddCategoryModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly IValidator<CreateCategoryCommand> _validatorCategory;
        private readonly IValidator<CreateCategoryTranslationCommand> _validatorCategoryTranslation;

        public AddCategoryModel(IMediator mediator, IValidator<CreateCategoryCommand> validatorCategory, IValidator<CreateCategoryTranslationCommand> validatorCategoryTranslation)
        {
            _mediator = mediator;
            _validatorCategory = validatorCategory;
            _validatorCategoryTranslation = validatorCategoryTranslation;
        }

        [BindProperty]
        public LanguageDto DefaultLanguage { get; set; }
        [BindProperty]
        public string TranslationTitle { get; set; }
        [BindProperty]
        public int LanguageId { get; set; }

        public async Task OnGetAsync()
        {
            DefaultLanguage = await _mediator.Send(new GetLanguageByCodeQuery(DefaultStrings.DefaultLanguageCode));
            LanguageId = DefaultLanguage.Id;
        }

        public async Task<ActionResult> OnPostCreateAsync()
        {
            int id;
            using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                try
                {
                    CreateCategoryCommand createCategoryCommand = new CreateCategoryCommand();

                    ValidationResult resultCategory = await _validatorCategory.ValidateAsync(createCategoryCommand);

                    if (!resultCategory.IsValid)
                    {
                        resultCategory.AddToModelState(this.ModelState);
                        DefaultLanguage = await _mediator.Send(new GetLanguageByCodeQuery(DefaultStrings.DefaultLanguageCode));
                        LanguageId = DefaultLanguage.Id;
                        scope.Dispose();
                        return Page();
                    }

                    id = await _mediator.Send(createCategoryCommand);

                    CreateCategoryTranslationCommand createCategoryTranslationCommand = new CreateCategoryTranslationCommand()
                    {
                        Title = TranslationTitle,
                        CategoryId = id,
                        LanguageId = LanguageId
                    };

                    await _mediator.Send(createCategoryTranslationCommand);
                    ValidationResult resultTranslation = await _validatorCategoryTranslation.ValidateAsync(createCategoryTranslationCommand);

                    if (!resultTranslation.IsValid)
                    {
                        resultCategory.AddToModelState(this.ModelState);
                        DefaultLanguage = await _mediator.Send(new GetLanguageByCodeQuery(DefaultStrings.DefaultLanguageCode));
                        LanguageId = DefaultLanguage.Id;
                        scope.Dispose();
                        return Page();
                    }
                }

                catch (Exception ex)
                {
                    scope.Dispose();
                    Log.Error(ex, "Something went wrong on category creation\n" + ex.StackTrace);
                    return new RedirectToPageResult("/Admin/Error", new { message = "Something went wrong during the operation, please try again or contact the support team.", entityName = "Categories" });
                }

                scope.Complete();
            }

            string _message = $"Category with Id = {id} was successfully created with default {DefaultLanguage.Title} transaltion";
            return new RedirectToPageResult("/Admin/Succeed", new { message = _message, entityName = "Categories" });
        }
    }
}

Presentation/Pages/Admin/Categories/Details.cshtml.cs
using Application.Common.Models;
using Application.CQRS.CategoryTranslations.Queries.GetCategoryTranslationByCategoryId;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;

namespace Presentation.Pages.Admin.Categ
{
    [Authorize(Roles = RoleAccessLevels.AdminAndModerator)]
    public class CategoryDetailsModel : PageModel
    {
        private readonly IMediator _mediator;

        public CategoryDetailsModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public List<CategoryTranslationDto> Translations { get; set; }
        public int CategoryId { get; set; }

        public async Task OnGetAsync(int id)
        {
            Translations = await _mediator.Send(new GetCategoryTranslationsByCategoryIdQuery(id));
            CategoryId = id;
        }
    }
}

Presentation/Pages/Admin/Categories/Edit.cshtml.cs
using Application.Common.Models;
using Application.CQRS.CategoryTranslations.Commands.UpdateCategoryTranslation;
using Application.CQRS.CategoryTranslations.Queries.GetCategoryTranslationById;
using Application.CQRS.Languages.Queries.GetLanguages;
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;
using Serilog;

namespace Presentation.Pages.Admin.Categ
{
    [Authorize(Roles = RoleAccessLevels.AdminAndModerator)]
    public class EditCategoryModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly IValidator<UpdateCategoryTranslationCommand> _validator;

        public EditCategoryModel(IMediator mediator, IValidator<UpdateCategoryTranslationCommand> validator)
        {
            _mediator = mediator;
            _validator = validator;
        }

        [BindProperty]
        public string Title { get; set; }
        [BindProperty]
        public int LanguageId { get; set; }
        [BindProperty]
        public int CategoryId { get; set; }
        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public List<LanguageDto> Languages { get; set; }

        public async Task OnGetAsync(int id)
        {
            await UpdateProperties(id);
        }

        public async Task<ActionResult> OnPostUpdateAsync()
        {
            UpdateCategoryTranslationCommand updateCategoryTranslationCommand;
            try
            {
                updateCategoryTranslationCommand = new UpdateCategoryTranslationCommand()
                {
                    Title = Title,
                    LanguageId = LanguageId,
                    CategoryId = CategoryId
                };

                ValidationResult result = await _validator.ValidateAsync(updateCategoryTranslationCommand);

                if (!result.IsValid)
                {
                    result.AddToModelState(this.ModelState);
                    await UpdateProperties(Id);
                    return Page();
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Something went wrong on updating category information\n" + ex.StackTrace);
                return new RedirectToPageResult("/Admin/Error", new { message = "Something went wrong during the operation, please try again or contact the support team.", entityName = "Categories" });
            }

            string _message = await _mediator.Send(updateCategoryTranslationCommand);
            return new RedirectToPageResult("/Admin/Succeed", new { message = _message, entityName = "Categories" });
        }

        private async Task<IActionResult> UpdateProperties(int id)
        {
            try
            {
                var categoryTranslation = await _mediator.Send(new GetCategoryTranslationByIdQuery(id));
                CategoryId = categoryTranslation.CategoryId;
                LanguageId = categoryTranslation.LanguageId;
                Title = categoryTranslation.Title;
                Id = id;

                Languages = await _mediator.Send(new GetLanguagesQuery());
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Something went wrong on updating page properties\n" + ex.StackTrace);
                return new RedirectToPageResult("/Admin/Error", new { message = "Something went wrong during the operation, please try again or contact the support team.", entityName = "Categories" });
            }

            return Page();
        }
    }
}

Presentation/Pages/Admin/Hashtags/Add.cshtml.cs
using Application.CQRS.Hashtags.Commands.CreateHashtag;
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;

namespace Presentation.Pages.Admin.Hash
{
    [Authorize(Roles = RoleAccessLevels.AllRoles)]
    public class AddHashtagModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly IValidator<CreateHashtagCommand> _validator;

        public AddHashtagModel(IMediator mediator, IValidator<CreateHashtagCommand> validator)
        {
            _validator = validator;
            _mediator = mediator;
        }

        [BindProperty]
        public string Title { get; set; }

        public async Task<ActionResult> OnPostCreateAsync()
        {
            CreateHashtagCommand command = new CreateHashtagCommand()
            {
                Title = Title
            };

            ValidationResult result = await _validator.ValidateAsync(command);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return Page();
            }

            int id = await _mediator.Send(command);

            string _message = $"Hashtag with Id = {id} was successfully created";

            return new RedirectToPageResult("/Admin/Succeed", new { message = _message, entityName = "Hashtags" });

        }
    }
}

Presentation/Pages/Admin/Hashtags/Details.cshtml.cs
using Application.Common.Models;
using Application.CQRS.Hashtags.Queries.GetHashtagById;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;
namespace Presentation.Pages.Admin.Hash
{
    [Authorize(Roles = RoleAccessLevels.AllRoles)]
    public class HashtagDetailsModel : PageModel
    {
        private readonly IMediator _mediator;

        public HashtagDetailsModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public HashtagDto Hashtag { get; set; }
        public async Task OnGetAsync(int Id)
        {
            Hashtag = await _mediator.Send(new GetHashtagByIdQuery(Id));
        }
    }
}

Presentation/Pages/Admin/Hashtags/Edit.cshtml.cs
using Application.Common.Models;
using Application.CQRS.Hashtags.Commands.UpdateHashtag;
using Application.CQRS.Hashtags.Queries.GetHashtagById;
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;

namespace Presentation.Pages.Admin.Hash
{
    [Authorize(Roles = RoleAccessLevels.AllRoles)]
    public class EditHashtagModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly IValidator<UpdateHashtagCommand> _validator;

        public EditHashtagModel(IMediator mediator, IValidator<UpdateHashtagCommand> validator)
        {
            _mediator = mediator;
            _validator = validator;
        }
        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public string Title { get; set; }


        public async Task OnGetAsync(int id)
        {
            HashtagDto hashtag = await _mediator.Send(new GetHashtagByIdQuery(id));
        }

        public async Task<ActionResult> OnPostUpdateAsync()
        {
            UpdateHashtagCommand command = new UpdateHashtagCommand()
            {
                Id = Id,
                Title = Title
            };

            ValidationResult result = await _validator.ValidateAsync(command);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return Page();
            }

            await _mediator.Send(command);
            string _message = $"Hashtag with Id = {command.Id} was updated successfully";
            return new RedirectToPageResult("/Admin/Succeed", new { message = _message, entityName = "Hashtags" });
        }
    }
}

Presentation/Pages/Admin/Languages/Details.cshtml.cs
using Application.Common.Models;
using Application.CQRS.Languages.Queries.GetLanguage;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;

namespace Presentation.Pages.Admin.Lan
{
    [Authorize(Roles = RoleAccessLevels.AdminOnly)]
    public class LanguageDetailsModel : PageModel
    {
        public LanguageDto Language { get; set; }
        private readonly IMediator _mediator;
        public LanguageDetailsModel(IMediator mediator)
        {
            _mediator = mediator;
        }
        public async Task OnGetAsync(int id)
        {
            GetLanguageByIdQuery getLanguageByIdQuery = new GetLanguageByIdQuery(id);
            Language = await _mediator.Send(getLanguageByIdQuery);
        }
    }
}

Presentation/Pages/Admin/Languages/Edit.cshtml.cs
using Application.Common.Models;
using Application.CQRS.Languages.Commands.UpdateLanguage;
using Application.CQRS.Languages.Queries.GetLanguage;
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;

namespace Presentation.Pages.Admin.Lan
{
    [Authorize(Roles = RoleAccessLevels.AdminOnly)]
    public class EditLanguageModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly IValidator<UpdateLanguageCommand> _validator;

        [BindProperty]
        public string Title { get; set; }
        [BindProperty]
        public string Code { get; set; }
        [BindProperty]
        public int Id { get; set; }

        public EditLanguageModel(IMediator mediator, IValidator<UpdateLanguageCommand> validator)
        {
            _mediator = mediator;
            _validator = validator;
        }

        public async Task OnGetAsync(int id)
        {
            GetLanguageByIdQuery getLanguageByIdQuery = new GetLanguageByIdQuery() { Id = id };
            LanguageDto language = await _mediator.Send(getLanguageByIdQuery);
            Title = language.Title;
            Code = language.Code;
            Id = language.Id;
        }

        public async Task<ActionResult> OnPostPutAsync()
        {
            UpdateLanguageCommand updateLanguageCommand = new UpdateLanguageCommand()
            {
                Id = Id,
                Code = Code,
                Title = Title
            };

            ValidationResult result = await _validator.ValidateAsync(updateLanguageCommand);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return Page();
            }

            await _mediator.Send(updateLanguageCommand);
            string _message = $"Language with Id = {Id} was successfully updated";
            return new RedirectToPageResult("/Admin/Succeed", new { message = _message, entityName = "Languages" });
        }


    }
}

Presentation/Pages/Admin/Languages/Index.cshtml.cs
using Application.Common.Models;
using Application.CQRS.Languages.Commands.DeleteLanguage;
using Application.CQRS.Languages.Queries.GetLanguages;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;

namespace Presentation.Pages.Admin.Lists
{
    [Authorize(Roles = RoleAccessLevels.AdminOnly)]
    public class LanguagesModel : PageModel
    {
        public List<LanguageDto> Languages { get; set; }
        private readonly IMediator _mediator;
        public LanguagesModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task OnGetAsync()
        {
            Languages = await _mediator.Send(new GetLanguagesQuery());
        }

        public async Task<IActionResult> OnPostDeleteAsync(int Id)
        {
            await _mediator.Send(new DeleteLanguageCommand(Id));

            string _message = $"Language with Id = {Id} was successfully deleted";

            return new RedirectToPageResult("/Admin/Succeed", new { message = _message, entityName = "Languages" });
        }
    }
}

Presentation/Pages/Admin/Languages/Add.cshtml
@page
@model Presentation.Pages.Admin.Lan.AddLanguageModel
@{
    ViewBag.Title = "Add Language";
}

<!-- Main content -->
<section class="content">
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">General</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="card-body">
            <form method="post" asp-page-handler="Save">
                <div class="form-group">
                    <label for="inputDescription">Title</label>
                    <input type="text" class="form-control" asp-for="Title">
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="inputName">Code</label>
                    <input type="text" id="inputName" class="form-control" asp-for="Code">
                    <span asp-validation-for="Code" class="text-danger"></span>
                </div>
                <div class="row">
                    <div class="col-12">
                        <a href="#" class="btn btn-secondary">Cancel</a>
                        <input type="submit" value="Save Changes" class="btn btn-success float-right">
                    </div>
                </div>
            </form>
            <!-- /.card-body -->
        </div>
    </div>
</section>

Presentation/Pages/Admin/Languages/Details.cshtml
@page
@model Presentation.Pages.Admin.Lan.LanguageDetailsModel
@{
    ViewBag.Title = "Language Details";
}
@using Application.Common.Models;
@using Domain.Entities;
<div style="margin: 10px;">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-text-width"></i>
                Details
            </h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <dl>
                @foreach (var property in typeof(LanguageDto).GetProperties())
                {                    
                    <dt>@property.Name</dt>
                    <dd>@property.GetValue(Model.Language)</dd>
                }
            </dl>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<!-- ./col -->

Presentation/Pages/Admin/Languages/Edit.cshtml
@page
@model Presentation.Pages.Admin.Lan.EditLanguageModel
@{
    ViewBag.Title = "Edit Language";
}

<!-- Main content -->
<section class="content">
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">General</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="card-body">
            <form method="post" asp-page-handler="Put">
                <input type="hidden" asp-for="Id" class="form-control" />
                <div class="form-group">
                    <label for="inputDescription">Title</label>
                    <input type="text" asp-for="Title" class="form-control">
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="inputName">Code</label>
                    <input type="text" asp-for="Code" class="form-control">
                    <span asp-validation-for="Code" class="text-danger"></span>
                </div>
                <div class="row">
                    <div class="col-12">
                        <a href="#" class="btn btn-secondary">Cancel</a>
                        <input type="submit" value="Save Changes" class="btn btn-success float-right">
                    </div>
                </div>
            </form>
            <!-- /.card-body -->
        </div>
    </div>
</section>

Presentation/Pages/Admin/Languages/Index.cshtml
@page
@using Domain.Entities;
@using Microsoft.AspNetCore.Identity;
@inject UserManager<User> UserManager;
@using Application.Common.Models;
@model Presentation.Pages.Admin.Lists.LanguagesModel
@{
    ViewBag.Title = "Languages";
    var currentUser = await UserManager.GetUserAsync(User);
    bool userIsAdmin = await UserManager.IsInRoleAsync(currentUser, "Admin");
}
<section class="content">
    <div class="card">
        <div class="card-header">
            <button type="button" onclick="location.href='@Url.Page("/Admin/Languages/Add")'" class="btn btn-primary">Add Language</button>

            <div class="card-tools">
                <button type="button" class="btn" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn" data-card-widget="remove" title="Remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        @foreach (var property in typeof(LanguageDto).GetProperties())
                        {
                            if (property.Name != "Id")
                            {
                                <th>@property.Name</th>
                            }
                        }
                        <th style="width: 20%">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (LanguageDto language in Model.Languages)
                    {
                        <tr>
                            @foreach (var property in typeof(LanguageDto).GetProperties())
                            {
                                if (property.Name != "Id")
                                {
                                    <td>@property.GetValue(language)</td>
                                }
                            }

                            <td class="project-actions text-right">
                                <form method="post">
                                    <a class="btn btn-primary btn-sm" asp-page="/Admin/Languages/Details"
                                       asp-route-id="@language.Id">
                                        <i class="fas fa-folder">
                                        </i>
                                        View
                                    </a>
                                    <a class="btn btn-info btn-sm" asp-page="/Admin/Languages/Edit"
                                       asp-route-id="@language.Id">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Edit
                                    </a>

                                    @if (userIsAdmin)
                                    {
                                        <button class="btn btn-danger btn-sm"
                                                type="submit"
                                                asp-page-handler="Delete"
                                                asp-route-id="@language.Id">
                                            <i class="fas fa-trash">
                                            </i>
                                            Delete
                                        </button>
                                    }
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>