Presentation/Pages/Admin/Approve/CategoryTranslationsStatus.cshtml.cs
using Application.Common.Models;
using Application.CQRS.CategoryTranslations.Commands.ChangeCategoryStatuses;
using Application.CQRS.CategoryTranslations.Queries.GetCategoryTranslations;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Presentation.Constants;

namespace Presentation.Pages.Admin.Approve
{
    [Authorize(Roles = RoleAccessLevels.AdminAndModerator)]
    public class CategoryTranslationsStatusModel : PageModel
    {
        private readonly IMediator _mediator;

        public CategoryTranslationsStatusModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public List<CategoryTranslationDto> Translations { get; set; }

        public async Task OnGetAsync()
        {
            await UpdateProperties();
        }

        public async Task OnPostChangeStatusAsync(string selectedvalues)
        {
            List<CategoryTranslationStatusObj> selectedCategories = JsonStringToList(selectedvalues);

            ChangeCategoryTranslationStatusesCommand command = new ChangeCategoryTranslationStatusesCommand()
            {
                ChangedCategories = selectedCategories
            };

            await _mediator.Send(command);
            await UpdateProperties();
        }

        private List<CategoryTranslationStatusObj> JsonStringToList(string json)
        {
            List<CategoryTranslationStatusObj> list = JsonConvert.DeserializeObject<List<CategoryTranslationStatusObj>>(json);
            return list;
        }

        private async Task UpdateProperties()
        {
            Translations = await _mediator.Send(new GetCategoryTranslationsQuery());
        }


    }
}

Presentation/Pages/Admin/Approve/PostTranslationsStatus.cshtml.cs
using Application.Common.Models;
using Application.CQRS.Languages.Queries.GetLanguageByCode;
using Application.CQRS.Posts.Queries.GetPostById;
using Application.CQRS.PostTranslations.Commands.ChangePostTranslationsStatuses;
using Application.CQRS.PostTranslations.Queries.GetPostTranslationsForApproval;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Presentation.Constants;

namespace Presentation.Pages.Admin.Approve
{
    [Authorize(Roles = RoleAccessLevels.AdminAndModerator)]
    public class PostTranslationsStatusModel : PageModel
    {
        private readonly IMediator _mediator;

        public PostTranslationsStatusModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public List<PostTranslationDto> Posts { get; set; }
        public LanguageDto DefaultLanguage { get; set; }

        public async Task OnGetAsync()
        {
            await UpdateProperties();
        }

        public async Task OnPostChangeStatusAsync(string selectedvalues)
        {
            List<PostTranslationStatusObj> selectedPosts = JsonStringToList(selectedvalues);

            ChangePostTranslationsStatusesCommand command = new ChangePostTranslationsStatusesCommand()
            {
                ChangedTranslations = selectedPosts
            };

            await _mediator.Send(command);
            await UpdateProperties();
        }

        private List<PostTranslationStatusObj> JsonStringToList(string json)
        {
            List<PostTranslationStatusObj> list = JsonConvert.DeserializeObject<List<PostTranslationStatusObj>>(json);
            return list;
        }

        private async Task UpdateProperties()
        {
            Posts = await _mediator.Send(new GetPostTranslationsForApprovalQuery());
            DefaultLanguage = await _mediator.Send(new GetLanguageByCodeQuery(DefaultStrings.DefaultLanguageCode));
        }

        public async Task<string> GetPostStatus(int postId)
        {
            var post = await _mediator.Send(new GetPostByIdQuery(postId));

            return post.Status;
        }
    }
}

Presentation/Pages/Admin/Approve/PostsStatus.cshtml.cs
using Application.Common.Models;
using Application.CQRS.Posts.Commands.ChangePostsStatuses;
using Application.CQRS.Posts.Queries.GetPostsForApproval;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Presentation.Constants;
using Serilog;
using System.Data.Common;

namespace Presentation.Pages.Admin.Approve
{
    [Authorize(Roles = RoleAccessLevels.AdminAndModerator)]
    public class PostsStatusModel : PageModel
    {
        private readonly IMediator _mediator;

        public PostsStatusModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public List<PostDto> Posts { get; set; }

        public async Task OnGetAsync()
        {
            await UpdateProperties();
        }

        public async Task<IActionResult> OnPostChangeStatusAsync(string selectedvalues)
        {
            List<PostStatusObj> selectedPosts = JsonStringToList(selectedvalues);

            ChangePostsStatusesCommand command = new ChangePostsStatusesCommand()
            {
                ChangedPosts = selectedPosts
            };

            try
            {
                await _mediator.Send(command);

            }
            catch (DbException dbEx)
            {
                Log.Error(dbEx, "An error occured during the database operation" + dbEx.StackTrace);
                return new RedirectToPageResult("/Admin/Error", new { message = "An unexpected error occured during the operation. Please try again or contact the support team.", entityName = "Posts" });
            }
            catch (Exception ex)
            {
                Log.Error(ex, "An unexpected error occured on post status updation");

                return new RedirectToPageResult("/Admin/Error", new { message = "An unexpected error occured during the operation. Please try again or contact the support team." });
            }

            await UpdateProperties();
            return Page();
        }

        private List<PostStatusObj> JsonStringToList(string json)
        {
            List<PostStatusObj> list = JsonConvert.DeserializeObject<List<PostStatusObj>>(json);
            return list;
        }

        private async Task UpdateProperties()
        {
            Posts = await _mediator.Send(new GetPostsForApprovalQuery());
        }
    }
}

Presentation/Pages/Admin/Approve/CategoryTranslationsStatus.cshtml
@page
@using Application.Common.Models;
@model Presentation.Pages.Admin.Approve.CategoryTranslationsStatusModel
@{
}
<form method="post" asp-page-handler="ChangeStatus">
    <section class="content">
        <div class="card" style="margin: 5px">
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            @foreach (var property in typeof(CategoryTranslationDto).GetProperties())
                            {
                                if (property.Name == "Id" || property.Name == "Title" || property.Name == "Status")
                                {
                                    <th>@property.Name</th>
                                }
                            }
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var translation in Model.Translations)
                        {
                            <tr>
                                @foreach (var property in typeof(CategoryTranslationDto).GetProperties())
                                {
                                    if (property.Name == "Id" || property.Name == "Title" || property.Name == "Status")
                                    {
                                        <td>@property.GetValue(translation)</td>
                                    }
                                }
                                <td class="project-actions text-right">
                                    <input type="hidden" name="id" value="@translation.Id" />
                                    <select name="status" id="inputStatus" class="form-control custom-select">
                                        <option selected disabled>Select status</option>
                                        <option>Published</option>
                                        <option>Pending</option>
                                        <option>Draft</option>                                        
                                        <option>Scheduled</option>
                                    </select>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <input type="hidden" name="selectedValues" id="selectedPosts" />
            </div>
        </div>
    </section>
    <button class="btn btn-primary btn-sm"
            id="buttonStatus"
            type="submit"
            style="margin: 5px; font-size: 15px">
        <i class="fas fa-check">
        </i>
        Change statuses
    </button>
</form>

@section Scripts {
    <script src="/js/status.js" asp-append-version="true"></script>
}

Presentation/Pages/Admin/Approve/PostTranslationsStatus.cshtml
@page
@using Application.Common.Models;
@model Presentation.Pages.Admin.Approve.PostTranslationsStatusModel
@{
}

<form method="post" asp-page-handler="ChangeStatus">
    <section class="content">
        <div class="card">
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            @foreach (var property in typeof(PostTranslationDto).GetProperties())
                            {
                                if (property.Name == "Id" || property.Name == "Title" || property.Name == "Status" || property.Name == "PostId")
                                {
                                    <th>@property.Name</th>
                                }
                            }
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (PostTranslationDto translation in Model.Posts)
                        {
                            <tr>
                                @foreach (var property in typeof(PostTranslationDto).GetProperties())
                                {
                                    if (property.Name == "Id" || property.Name == "Title" || property.Name == "Status" || property.Name == "PostId")
                                    {
                                        <td>@property.GetValue(translation)</td>
                                    }
                                }
                                <td class="project-actions text-right">
                                    <input type="hidden" name="id" value="@translation.Id" />
                                    @{
                                        var postStatus = await Model.GetPostStatus(translation.PostId);
                                    }
                                    @if (postStatus == "Published" && translation.LanguageId == Model.DefaultLanguage.Id)
                                    {
                                        <p>The post you are trying to edit is currently in 'Published' status. The default translation cannot be modified.</p>
                                    }
                                    else
                                    {
                                        <select name="status" id="inputStatus" class="form-control custom-select">
                                            <option selected disabled>Select status</option>
                                            @if (postStatus == "Published")
                                            {
                                                <option>Published</option>
                                            }
                                            <option>Pending</option>
                                            <option>Draft</option>
                                            @if (translation.LanguageId != Model.DefaultLanguage.Id)
                                            {
                                                <option>Deleted</option>
                                            }
                                            <option>Scheduled</option>
                                        </select>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <input type="hidden" name="selectedValues" id="selectedPosts" />
            </div>
        </div>
    </section>
    <button class="btn btn-primary btn-sm"
            id="buttonStatus"
            type="submit"
            style="margin: 5px; font-size: 15px">
        <i class="fas fa-check">
        </i>
        Change statuses
    </button>
</form>

@section Scripts {
    <script src="~/js/status.js" asp-append-version="true"></script>
}                                            

Presentation/Pages/Admin/Approve/PostsStatus.cshtml
@page
@using Application.Common.Models;
@model Presentation.Pages.Admin.Approve.PostsStatusModel
@{
}

<form method="post" asp-page-handler="ChangeStatus">
    <section class="content">
        <div class="card" style="margin: 5px">
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            @foreach (var property in typeof(PostDto).GetProperties())
                            {
                                if (property.Name == "Id" || property.Name == "CategoryId" || property.Name == "Status")
                                {
                                    <th>@property.Name</th>
                                }
                            }
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var post in Model.Posts)
                        {
                            <tr>
                                @foreach (var property in typeof(PostDto).GetProperties())
                                {
                                    if (property.Name == "Id" || property.Name == "CategoryId" || property.Name == "Status")
                                    {
                                        <td>@property.GetValue(post)</td>
                                    }
                                }
                                <td class="project-actions text-right">
                                    <input type="hidden" name="id" value="@post.Id" />
                                    <select name="status" id="inputStatus" class="form-control custom-select">
                                        <option selected disabled>Select status</option>
                                        <option>Published</option>
                                        <option>Pending</option>
                                        <option>Draft</option>
                                        <option>Deleted</option>
                                        <option>Scheduled</option>
                                    </select>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <input type="hidden" name="selectedValues" id="selectedPosts" />
            </div>
        </div>
    </section>
    <button class="btn btn-primary btn-sm"
            id="buttonStatus"
            type="submit"
            style="margin: 5px; font-size: 15px">
        <i class="fas fa-check">
        </i>
        Change statuses
    </button>
</form>

@section Scripts{
    <script src="~/js/status.js" asp-append-version="true"></script>
}   