Presentation/Pages/Admin/Categories/Add.cshtml.cs
using Application.Common.Models;
using Application.CQRS.Categories.Commands.CreateCategory;
using Application.CQRS.CategoryTranslations.Commands.CreateCategoryTranslation;
using Application.CQRS.Languages.Queries.GetLanguageByCode;
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;
using Serilog;
using System.Transactions;

namespace Presentation.Pages.Admin.Categ
{
    [Authorize(Roles = RoleAccessLevels.AdminAndModerator)]
    public class AddCategoryModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly IValidator<CreateCategoryCommand> _validatorCategory;
        private readonly IValidator<CreateCategoryTranslationCommand> _validatorCategoryTranslation;

        public AddCategoryModel(IMediator mediator, IValidator<CreateCategoryCommand> validatorCategory, IValidator<CreateCategoryTranslationCommand> validatorCategoryTranslation)
        {
            _mediator = mediator;
            _validatorCategory = validatorCategory;
            _validatorCategoryTranslation = validatorCategoryTranslation;
        }

        [BindProperty]
        public LanguageDto DefaultLanguage { get; set; }
        [BindProperty]
        public string TranslationTitle { get; set; }
        [BindProperty]
        public int LanguageId { get; set; }

        public async Task OnGetAsync()
        {
            DefaultLanguage = await _mediator.Send(new GetLanguageByCodeQuery(DefaultStrings.DefaultLanguageCode));
            LanguageId = DefaultLanguage.Id;
        }

        public async Task<ActionResult> OnPostCreateAsync()
        {
            int id;
            using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                try
                {
                    CreateCategoryCommand createCategoryCommand = new CreateCategoryCommand();

                    ValidationResult resultCategory = await _validatorCategory.ValidateAsync(createCategoryCommand);

                    if (!resultCategory.IsValid)
                    {
                        resultCategory.AddToModelState(this.ModelState);
                        DefaultLanguage = await _mediator.Send(new GetLanguageByCodeQuery(DefaultStrings.DefaultLanguageCode));
                        LanguageId = DefaultLanguage.Id;
                        scope.Dispose();
                        return Page();
                    }

                    id = await _mediator.Send(createCategoryCommand);

                    CreateCategoryTranslationCommand createCategoryTranslationCommand = new CreateCategoryTranslationCommand()
                    {
                        Title = TranslationTitle,
                        CategoryId = id,
                        LanguageId = LanguageId
                    };

                    await _mediator.Send(createCategoryTranslationCommand);
                    ValidationResult resultTranslation = await _validatorCategoryTranslation.ValidateAsync(createCategoryTranslationCommand);

                    if (!resultTranslation.IsValid)
                    {
                        resultCategory.AddToModelState(this.ModelState);
                        DefaultLanguage = await _mediator.Send(new GetLanguageByCodeQuery(DefaultStrings.DefaultLanguageCode));
                        LanguageId = DefaultLanguage.Id;
                        scope.Dispose();
                        return Page();
                    }
                }

                catch (Exception ex)
                {
                    scope.Dispose();
                    Log.Error(ex, "Something went wrong on category creation\n" + ex.StackTrace);
                    return new RedirectToPageResult("/Admin/Error", new { message = "Something went wrong during the operation, please try again or contact the support team.", entityName = "Categories" });
                }

                scope.Complete();
            }

            string _message = $"Category with Id = {id} was successfully created with default {DefaultLanguage.Title} transaltion";
            return new RedirectToPageResult("/Admin/Succeed", new { message = _message, entityName = "Categories" });
        }
    }
}

Presentation/Pages/Admin/Categories/Details.cshtml.cs
using Application.Common.Models;
using Application.CQRS.CategoryTranslations.Queries.GetCategoryTranslationByCategoryId;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;

namespace Presentation.Pages.Admin.Categ
{
    [Authorize(Roles = RoleAccessLevels.AdminAndModerator)]
    public class CategoryDetailsModel : PageModel
    {
        private readonly IMediator _mediator;

        public CategoryDetailsModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public List<CategoryTranslationDto> Translations { get; set; }
        public int CategoryId { get; set; }

        public async Task OnGetAsync(int id)
        {
            Translations = await _mediator.Send(new GetCategoryTranslationsByCategoryIdQuery(id));
            CategoryId = id;
        }
    }
}

Presentation/Pages/Admin/Categories/Edit.cshtml.cs
using Application.Common.Models;
using Application.CQRS.CategoryTranslations.Commands.UpdateCategoryTranslation;
using Application.CQRS.CategoryTranslations.Queries.GetCategoryTranslationById;
using Application.CQRS.Languages.Queries.GetLanguages;
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;
using Serilog;

namespace Presentation.Pages.Admin.Categ
{
    [Authorize(Roles = RoleAccessLevels.AdminAndModerator)]
    public class EditCategoryModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly IValidator<UpdateCategoryTranslationCommand> _validator;

        public EditCategoryModel(IMediator mediator, IValidator<UpdateCategoryTranslationCommand> validator)
        {
            _mediator = mediator;
            _validator = validator;
        }

        [BindProperty]
        public string Title { get; set; }
        [BindProperty]
        public int LanguageId { get; set; }
        [BindProperty]
        public int CategoryId { get; set; }
        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public List<LanguageDto> Languages { get; set; }

        public async Task OnGetAsync(int id)
        {
            await UpdateProperties(id);
        }

        public async Task<ActionResult> OnPostUpdateAsync()
        {
            UpdateCategoryTranslationCommand updateCategoryTranslationCommand;
            try
            {
                updateCategoryTranslationCommand = new UpdateCategoryTranslationCommand()
                {
                    Title = Title,
                    LanguageId = LanguageId,
                    CategoryId = CategoryId
                };

                ValidationResult result = await _validator.ValidateAsync(updateCategoryTranslationCommand);

                if (!result.IsValid)
                {
                    result.AddToModelState(this.ModelState);
                    await UpdateProperties(Id);
                    return Page();
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Something went wrong on updating category information\n" + ex.StackTrace);
                return new RedirectToPageResult("/Admin/Error", new { message = "Something went wrong during the operation, please try again or contact the support team.", entityName = "Categories" });
            }

            string _message = await _mediator.Send(updateCategoryTranslationCommand);
            return new RedirectToPageResult("/Admin/Succeed", new { message = _message, entityName = "Categories" });
        }

        private async Task<IActionResult> UpdateProperties(int id)
        {
            try
            {
                var categoryTranslation = await _mediator.Send(new GetCategoryTranslationByIdQuery(id));
                CategoryId = categoryTranslation.CategoryId;
                LanguageId = categoryTranslation.LanguageId;
                Title = categoryTranslation.Title;
                Id = id;

                Languages = await _mediator.Send(new GetLanguagesQuery());
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Something went wrong on updating page properties\n" + ex.StackTrace);
                return new RedirectToPageResult("/Admin/Error", new { message = "Something went wrong during the operation, please try again or contact the support team.", entityName = "Categories" });
            }

            return Page();
        }
    }
}

Presentation/Pages/Admin/Categories/Index.cshtml.cs
using Application.Common.Models;
using Application.CQRS.Categories.Commands.DeleteCategory;
using Application.CQRS.CategoryTranslations.Queries.GetCategoryTranslationsByLanguageId;
using Application.CQRS.Languages.Queries.GetLanguageByCode;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;
using Serilog;

namespace Presentation.Pages.Admin.Lists
{
    [Authorize(Roles = RoleAccessLevels.AllRoles)]
    public class CategoriesModel : PageModel
    {
        private readonly IMediator _mediator;

        public CategoriesModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public List<CategoryTranslationDto> Categories { get; set; }

        public async Task OnGetAsync()
        {
            var defaultLanguage = await _mediator.Send(new GetLanguageByCodeQuery(DefaultStrings.DefaultLanguageCode));
            Categories = await _mediator.Send(new GetCategoryTranslationsByLanguageIdQuery(defaultLanguage.Id));
        }

        public async Task<ActionResult> OnPostDeleteAsync(int id)
        {
            DeleteCategoryCommand command = new DeleteCategoryCommand(id);

            try
            {
                await _mediator.Send(command);
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Something went wrong on deleting category\n" + ex.StackTrace);
                return new RedirectToPageResult("/Admin/Error", new { message = "Something went wrong during the operation, please try again or contact the support team.", entityName = "Categories" });
            }

            string _message = $"Category with Id = {id} and all related translations were deleted";

            return new RedirectToPageResult("/Admin/Succeed", new { message = _message, entityName = "Categories" });
        }
    }
}

Presentation/Pages/Admin/Hashtags/Add.cshtml.cs
using Application.CQRS.Hashtags.Commands.CreateHashtag;
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;

namespace Presentation.Pages.Admin.Hash
{
    [Authorize(Roles = RoleAccessLevels.AllRoles)]
    public class AddHashtagModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly IValidator<CreateHashtagCommand> _validator;

        public AddHashtagModel(IMediator mediator, IValidator<CreateHashtagCommand> validator)
        {
            _validator = validator;
            _mediator = mediator;
        }

        [BindProperty]
        public string Title { get; set; }

        public async Task<ActionResult> OnPostCreateAsync()
        {
            CreateHashtagCommand command = new CreateHashtagCommand()
            {
                Title = Title
            };

            ValidationResult result = await _validator.ValidateAsync(command);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return Page();
            }

            int id = await _mediator.Send(command);

            string _message = $"Hashtag with Id = {id} was successfully created";

            return new RedirectToPageResult("/Admin/Succeed", new { message = _message, entityName = "Hashtags" });

        }
    }
}

Presentation/Pages/Admin/Hashtags/Details.cshtml.cs
using Application.Common.Models;
using Application.CQRS.Hashtags.Queries.GetHashtagById;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;
namespace Presentation.Pages.Admin.Hash
{
    [Authorize(Roles = RoleAccessLevels.AllRoles)]
    public class HashtagDetailsModel : PageModel
    {
        private readonly IMediator _mediator;

        public HashtagDetailsModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public HashtagDto Hashtag { get; set; }
        public async Task OnGetAsync(int Id)
        {
            Hashtag = await _mediator.Send(new GetHashtagByIdQuery(Id));
        }
    }
}

Presentation/Pages/Admin/Hashtags/Edit.cshtml.cs
using Application.Common.Models;
using Application.CQRS.Hashtags.Commands.UpdateHashtag;
using Application.CQRS.Hashtags.Queries.GetHashtagById;
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;

namespace Presentation.Pages.Admin.Hash
{
    [Authorize(Roles = RoleAccessLevels.AllRoles)]
    public class EditHashtagModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly IValidator<UpdateHashtagCommand> _validator;

        public EditHashtagModel(IMediator mediator, IValidator<UpdateHashtagCommand> validator)
        {
            _mediator = mediator;
            _validator = validator;
        }
        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public string Title { get; set; }


        public async Task OnGetAsync(int id)
        {
            HashtagDto hashtag = await _mediator.Send(new GetHashtagByIdQuery(id));
        }

        public async Task<ActionResult> OnPostUpdateAsync()
        {
            UpdateHashtagCommand command = new UpdateHashtagCommand()
            {
                Id = Id,
                Title = Title
            };

            ValidationResult result = await _validator.ValidateAsync(command);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return Page();
            }

            await _mediator.Send(command);
            string _message = $"Hashtag with Id = {command.Id} was updated successfully";
            return new RedirectToPageResult("/Admin/Succeed", new { message = _message, entityName = "Hashtags" });
        }
    }
}

Presentation/Pages/Admin/Languages/Add.cshtml.cs
using Application.CQRS.Languages.Commands.CreateLanguage;
using FluentValidation;
using FluentValidation.AspNetCore;
using FluentValidation.Results;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;

namespace Presentation.Pages.Admin.Lan
{
    [Authorize(Roles = RoleAccessLevels.AdminOnly)]
    public class AddLanguageModel : PageModel
    {
        private readonly IMediator _mediator;
        private readonly IValidator<CreateLanguageCommand> _validator;

        public AddLanguageModel(IMediator mediator, IValidator<CreateLanguageCommand> validator)
        {
            _mediator = mediator;
            _validator = validator;
        }

        [BindProperty]
        public string Title { get; init; }
        [BindProperty]
        public string Code { get; init; }

        public void OnGet()
        {

        }

        public async Task<ActionResult> OnPostAsync()
        {
            CreateLanguageCommand createLanguageCommand = new CreateLanguageCommand()
            {
                Code = Code,
                Title = Title
            };

            ValidationResult result = await _validator.ValidateAsync(createLanguageCommand);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return Page();
            }


            int id = await _mediator.Send(createLanguageCommand);
            string _message = $"Language with ID = {id} was successfully created";
            return RedirectToPage("/Admin/Succeed", new { message = _message, entityName = "Languages" });
        }
    }
}

Presentation/Pages/Admin/Languages/Details.cshtml.cs
using Application.Common.Models;
using Application.CQRS.Languages.Queries.GetLanguage;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Presentation.Constants;

namespace Presentation.Pages.Admin.Lan
{
    [Authorize(Roles = RoleAccessLevels.AdminOnly)]
    public class LanguageDetailsModel : PageModel
    {
        public LanguageDto Language { get; set; }
        private readonly IMediator _mediator;
        public LanguageDetailsModel(IMediator mediator)
        {
            _mediator = mediator;
        }
        public async Task OnGetAsync(int id)
        {
            GetLanguageByIdQuery getLanguageByIdQuery = new GetLanguageByIdQuery(id);
            Language = await _mediator.Send(getLanguageByIdQuery);
        }
    }
}

Presentation/Pages/Admin/Categories/Add.cshtml
@page
@using Application.Common.Models;
@model Presentation.Pages.Admin.Categ.AddCategoryModel
@{
    ViewBag.Title = "Add Category";
}
<!-- Main content -->
<section class="content">
    <form method="post" asp-page-handler="Create">
        <div class="card card-info">
            <div class="card-header">
                <h3 class="card-title">Default @Model.DefaultLanguage.Title translation</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="card-body">
                <input type="hidden" asp-for="LanguageId" />
                <div class="form-group">
                    <label for="inputDescription">Title</label>
                    <input type="text" asp-for="TranslationTitle" class="form-control" />
                    <span asp-validation-for="TranslationTitle" class="text-danger"></span>
                </div>
                <div class="row">
                    <div class="col-12">
                        <a href="#" class="btn btn-secondary">Cancel</a>
                        <input type="submit" value="Save Changes" class="btn btn-success float-right">
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>

Presentation/Pages/Admin/Categories/Details.cshtml
@page
@model Presentation.Pages.Admin.Categ.CategoryDetailsModel
@{
    ViewBag.Title = "Category Details";
}
@using Application.Common.Models;
<div style="margin: 10px;">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-text-width"></i>
                Category Id: @Model.CategoryId
            </h3>
        </div>

        <div class="card-body">
            @foreach (var translation in Model.Translations)
            {
                <dl>
                    @foreach (var property in typeof(CategoryTranslationDto).GetProperties())
                    {
                        if (property.Name != "CategoryId")
                        {
                            <dt>@property.Name</dt>
                            <dd>@property.GetValue(translation)</dd>
                        }
                    }
                </dl>
                <br />
            }
        </div>
    </div>
</div>

Presentation/Pages/Admin/Categories/Edit.cshtml
@page
@using Application.Common.Models;
@model Presentation.Pages.Admin.Categ.EditCategoryModel
@{
    ViewBag.Title = "Edit category";
}

<section class="content">
    <form method="post" asp-page-handler="Update">
        <div class="card card-info">
            <div class="card-header">
                <h3 class="card-title">Edit translation</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="card-body">
                <input type="hidden" asp-for="CategoryId" class="form-control" />
                <input type="hidden" asp-for="Id" class="form-control" />
                <div class="form-group">
                    <label for="inputDescription">Title</label>
                    <input type="text" asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="inputName">Language ID</label>
                    <select id="inputStatus" asp-for="LanguageId" class="form-control custom-select">
                        <option selected disabled>Select one</option>
                        @foreach (LanguageDto language in Model.Languages)
                        {
                            <option value="@language.Id">
                                <div>@language.Id - @language.Title</div>
                            </option>
                        }
                    </select>
                </div>
                <div class="row">
                    <div class="col-12">
                        <a href="#" class="btn btn-secondary">Cancel</a>
                        <input type="submit" value="Save Changes" class="btn btn-success float-right">
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>

Presentation/Pages/Admin/Categories/Index.cshtml
@page
@using Domain.Entities;
@using Microsoft.AspNetCore.Identity;
@inject UserManager<User> UserManager;
@model Presentation.Pages.Admin.Lists.CategoriesModel
@{
    ViewBag.Title = "Categories";
    var currentUser = await UserManager.GetUserAsync(User);
    bool userIsAdmin = await UserManager.IsInRoleAsync(currentUser, "Admin");
}
@using Application.Common.Models;
<section class="content">
    <div class="card">
        <div class="card-header">
            <button type="button" onclick="location.href='@Url.Page("/Admin/Category/Add")'" class="btn btn-primary">Add Category</button>

            <div class="card-tools">
                <button type="button" class="btn " data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn " data-card-widget="remove" title="Remove">
                    <i class="fas fa-times"></i>
                </button>

            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        @foreach (var property in typeof(CategoryTranslationDto).GetProperties())
                        {
                            if (property.Name != "Id")
                            {
                                <th>@property.Name</th>
                            }
                        }
                        <th style="width: 20%">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var category in Model.Categories)
                    {
                        <tr>
                            @foreach (var property in typeof(CategoryTranslationDto).GetProperties())
                            {
                                if (property.Name != "Id")
                                {
                                    <td>@property.GetValue(category)</td>
                                }
                            }
                            <td class="project-actions text-right">
                                <form method="post">
                                    <a class="btn btn-primary btn-sm"
                                       asp-page="/Admin/Category/Details"
                                       asp-route-id="@category.CategoryId">
                                        <i class="fas fa-folder"></i>
                                        View
                                    </a>
                                    <a class="btn btn-info btn-sm"
                                       asp-page="/Admin/Category/Edit"
                                       asp-route-id="@category.Id">
                                        <i class="fas fa-pencil-alt"></i>
                                        Edit
                                    </a>

                                    @if (userIsAdmin)
                                    {
                                    <button class="btn btn-danger btn-sm"
                                            type="submit"
                                            asp-page-handler="Delete"
                                            asp-route-id="@category.CategoryId">
                                        <i class="fas fa-trash">
                                        </i>
                                        Delete
                                    </button>
                                    }
                                </form>
                            </td>
                        </tr>

                    }
                </tbody>
            </table>
        </div>
    </div>
</section>